### ISSUE TITLE
Server can't start

### ISSUE THREAD

**Issue by amadin** [Kilarin/compassgps#8] opened 2015-07-31 12:58 UTC
After server(0.4.12-dev) crash without errors autorestart script try run server again, but it can't start. Server is public. Before last crash i set enable_rollback_recording = true

compassgps reading bookmarks
compassgps reading settings
2015-07-31 03:04:03: ERROR[main]: ========== ERROR FROM LUA ===========
2015-07-31 03:04:03: ERROR[main]: Failed to load and run script from 
2015-07-31 03:04:03: ERROR[main]: /home/user/minetest/bin/../games/minetest_game/mods/compassgps/init.lua:
2015-07-31 03:04:03: ERROR[main]: .../bin/../games/minetest_game/mods/compassgps/init.lua:144: bad argument #1 to 'pairs' (table expected, got nil)
2015-07-31 03:04:03: ERROR[main]: stack traceback:
2015-07-31 03:04:03: ERROR[main]:   [C]: in function 'pairs'
2015-07-31 03:04:03: ERROR[main]:   .../bin/../games/minetest_game/mods/compassgps/init.lua:144: in main chunk
2015-07-31 03:04:03: ERROR[main]: ======= END OF ERROR FROM LUA ========
2015-07-31 03:04:03: ERROR[main]: Server: Failed to load and run /home/user/minetest/bin/../games/minetest_game/mods/compassgps/init.lua
2015-07-31 03:04:03: ERROR[main]: ERROR: An unhandled exception occurred: ModError: Failed to load and run /home/user/minetest/bin/../games/minetest_game/mods/compassgps/init.lua
2015-07-31 03:04:03: ERROR[main]: Error from Lua:
2015-07-31 03:04:03: ERROR[main]: .../bin/../games/minetest_game/mods/compassgps/init.lua:144: bad argument #1 to 'pairs' (table expected, got nil)
2015-07-31 03:04:03: ERROR[main]: stack traceback:
2015-07-31 03:04:03: ERROR[main]:   [C]: in function 'pairs'
2015-07-31 03:04:03: ERROR[main]:   .../bin/../games/minetest_game/mods/compassgps/init.lua:144: in main chunk

**Comment by Kilarin** [comment] 2015-07-31 18:06
Yikes!   This was working before the crash I assume?
Can you upload a copy of your bookmarks file?  Should be .minetest/worlds/_worldname_/bookmarks 
and your settings file:  .minetest/worlds/_worldname_/compassgps_settings

Looks to me like its in the settings file.

Two problems to fix here, #1, what is messed up thats causing this to crash, and #2, even if the bookmark or settings file is corrupt, it shouldnt crash the server!!!!

**Comment by Kilarin** [comment] 2015-07-31 18:09
Oh, and in the meantime, if you just rename compassgps_settings and bookmarks (Keep the old files please) I bet that will get the server up.   But everyone will lose their settings and bookmarks until we figure out what is wrong with the files.
OR, if you happen to have a backup of those files from before the crash, use the old version.

**Comment by amadin** [comment] 2015-07-31 18:38
File compassgps_settings are empty (size 0 byte), file bookmarks:

return {["Brabusmese"] = {["y"] = -289.5, ["type"] = "P", ["z"] = -1136, ["bkmrkname"] = "mese", ["player"] = "Brabus", ["x"] = -294}, ["Brabusdiamant"] = {["y"] = -171.5, ["type"] = "P", ["z"] = -322, ["bkmrkname"] = "diamant", ["player"] = "Brabus", ["x"] = -1407}, ["okillerspawn"] = {["y"] = 6.5, ["type"] = "P", ["z"] = -193, ["bkmrkname"] = "spawn", ["player"] = "okiller", ["x"] = -269}, ["Andrey1Home"] = {["y"] = 5, ["player"] = "Andrey1", ["z"] = -186, ["bkmrkname"] = "Home", ["x"] = -245, ["type"] = "P"}, ["narrnikamy_home"] = {["y"] = -33, ["player"] = "narrnika", ["z"] = -356, ["bkmrkname"] = "my_home", ["x"] = -378, ["type"] = "P"}, ["electronic_stevehome"] = {["y"] = 13.5, ["type"] = "P", ["z"] = -370, ["bkmrkname"] = "home", ["player"] = "electronic_steve", ["x"] = -209}, ["mikolaîâöè"] = {["y"] = 5, ["player"] = "mikola", ["z"] = 437, ["bkmrkname"] = "îâöè", ["x"] = -215, ["type"] = "P"}, ["Brabuspeshchera"] = {["y"] = -1141.5, ["type"] = "P", ["z"] = -332, ["bkmrkname"] = "peshchera", ["x"] = -402, ["player"] = "Brabus"}, ["mikolaäîì"] = {["y"] = 0, ["player"] = "mikola", ["z"] = 33, ["bkmrkname"] = "äîì", ["x"] = 751, ["type"] = "P"}, ["BabaBombamonster"] = {["y"] = -176.5, ["type"] = "P", ["z"] = -312, ["bkmrkname"] = "monster", ["x"] = -402, ["player"] = "BabaBomba"}, ["BrabusBrabus_home"] = {["y"] = 4.5, ["type"] = "P", ["z"] = -1101, ["bkmrkname"] = "Brabus_home", ["player"] = "Brabus", ["x"] = -251}, ["VictorVictor"] = {["y"] = -100, ["player"] = "Victor", ["z"] = -186, ["bkmrkname"] = "Victor", ["x"] = -608, ["type"] = "P"}, ["KoZaspawn"] = {["y"] = 6.5, ["type"] = "P", ["z"] = -193, ["bkmrkname"] = "spawn", ["player"] = "KoZa", ["x"] = -269}, ["BabaBombamy"] = {["y"] = -107.5, ["type"] = "P", ["z"] = -318, ["bkmrkname"] = "my", ["x"] = -408, ["player"] = "BabaBomba"}, ["BrabusDiamant"] = {["y"] = -260.5, ["type"] = "P", ["z"] = -1135, ["bkmrkname"] = "Diamant", ["player"] = "Brabus", ["x"] = -296}, ["antonspawn dom"] = {["y"] = 6.5, ["type"] = "P", ["z"] = -193, ["bkmrkname"] = "spawn dom", ["x"] = -269, ["player"] = "anton"}, ["antonspawn"] = {["y"] = 6.5, ["type"] = "P", ["z"] = -193, ["bkmrkname"] = "spawn", ["x"] = -269, ["player"] = "anton"}, ["Brabusmonster"] = {["y"] = -151.5, ["type"] = "P", ["z"] = -327, ["bkmrkname"] = "monster", ["player"] = "Brabus", ["x"] = -1408}, ["Brabuslava"] = {["y"] = 14.5, ["type"] = "P", ["z"] = -750, ["bkmrkname"] = "lava", ["x"] = -1061, ["player"] = "Brabus"}, ["narrnikainput_to_home"] = {["y"] = 6, ["player"] = "narrnika", ["z"] = -193, ["bkmrkname"] = "input_to_home", ["x"] = -269, ["type"] = "P"}, ["DrWhohome"] = {["y"] = 30, ["player"] = "DrWho", ["z"] = -290, ["bkmrkname"] = "home", ["x"] = -24, ["type"] = "P"}, ["BabaBombamesse"] = {["y"] = -250.5, ["type"] = "P", ["z"] = -313, ["bkmrkname"] = "messe", ["x"] = -387, ["player"] = "BabaBomba"}, ["okillerokiller"] = {["y"] = 6.5, ["type"] = "P", ["z"] = -193, ["bkmrkname"] = "okiller", ["player"] = "okiller", ["x"] = -269}, ["nidamaÐÐµÑ ÐœÐ° Ð²ÐŸÑÑÐŸÐºÐµ"] = {["y"] = 5.6, ["type"] = "P", ["z"] = -835, ["bkmrkname"] = "ÐÐµÑ ÐœÐ° Ð²ÐŸÑÑÐŸÐºÐµ", ["x"] = -256, ["player"] = "nidama"}, ["NatekDOMEK NA DZEWIE"] = {["y"] = 6.5, ["type"] = "P", ["z"] = -193, ["bkmrkname"] = "DOMEK NA DZEWIE", ["player"] = "Natek", ["x"] = -269}, ["narrnikapole"] = {["y"] = 1, ["player"] = "narrnika", ["z"] = -535, ["bkmrkname"] = "pole", ["x"] = -156, ["type"] = "P"}, ["BrabusLes_KoZa_house"] = {["y"] = 8.5, ["type"] = "P", ["z"] = -720, ["bkmrkname"] = "Les_KoZa_house", ["x"] = -1313, ["player"] = "Brabus"}}

If i rename compassgps_settings and bookmarks, may compass error repeat?

**Comment by Kilarin** [comment] 2015-07-31 19:23
Great!  I've reproduced the problem!
The problem is that bookmarks is not blank, but compassgps_settings IS blank.
if you delete the blank compassgps_settings file, it should be rebuilt correctly on restart.

Will the error repeat?  I don't THINK so, what happened was that you had a crash and somehow, the compassgps_settings file ended up blank afterwards.  And the code crashes when that happens when it should just recreate it.

I will get to work on correcting the code so that it will not crash if this happens in the future.

Very sorry!

**Comment by Kilarin** [comment] 2015-07-31 19:24
to clarify, you should NOT have to delete the bookmarks file, so you won't lose everyone's bookmarks, they will only lose their compass settings, which are not very important.

**Comment by Kilarin** [comment] 2015-07-31 20:48
2.7 version committed that should correct this problem from every happening again.
https://github.com/Kilarin/compassgps/archive/master.zip

new version checks to see if the settings or bookmark files are empty, and if so, resets the tables to empty instead of nil (avoiding the crash) and then prints a warning message in debug telling the server owner to restore bookmarks/settings from backup if possible.

Thank you for reporting the error and sorry for the troubles!

**Closed as completed** 2016-10-22 06:36 UTC
